FROM golang:1.18 as builder

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ADD . /rcon-cli
WORKDIR /rcon-cli

RUN ./scripts/local/compile.sh 0.0.0

# Package Stage
FROM debian:bookworm-slim
COPY --from=builder /rcon-cli/gorcon /