# Stage 1 - Build
FROM golang:1.21-alpine AS builder

RUN apk --no-cache add gcc musl-dev

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY cmd cmd
COPY internal internal
RUN CGO_ENABLED=1 go build -o gorcon ./cmd/gorcon/main.go

# Stage 2 - Mayhem target image
FROM alpine:3.18

RUN apk --no-cache add libc6-compat

COPY --from=builder /build/gorcon /gorcon

CMD ["/gorcon"]
